//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/CardGame.proto
namespace proto.CardGame
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardGameArg")]
  public partial class CardGameArg : global::ProtoBuf.IExtensible
  {
    public CardGameArg() {}
    
    private int _cardId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardGameRes")]
  public partial class CardGameRes : global::ProtoBuf.IExtensible
  {
    public CardGameRes() {}
    
    private bool _isGameOver = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isGameOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isGameOver
    {
      get { return _isGameOver; }
      set { _isGameOver = value; }
    }
    private int _isWin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isWin
    {
      get { return _isWin; }
      set { _isWin = value; }
    }
    private bool _isTurnOver = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isTurnOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isTurnOver
    {
      get { return _isTurnOver; }
      set { _isTurnOver = value; }
    }
    private bool _isPlayerConfirmed = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isPlayerConfirmed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPlayerConfirmed
    {
      get { return _isPlayerConfirmed; }
      set { _isPlayerConfirmed = value; }
    }
    private int _playerCardId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerCardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerCardId
    {
      get { return _playerCardId; }
      set { _playerCardId = value; }
    }
    private int _playerHp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerHp
    {
      get { return _playerHp; }
      set { _playerHp = value; }
    }
    private int _selfHp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"selfHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfHp
    {
      get { return _selfHp; }
      set { _selfHp = value; }
    }
    private int _selfScore = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"selfScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfScore
    {
      get { return _selfScore; }
      set { _selfScore = value; }
    }
    private int _selfEnergy = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"selfEnergy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfEnergy
    {
      get { return _selfEnergy; }
      set { _selfEnergy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}