//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/FriendOperation.proto
namespace proto.FriendOperation
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendOperationArg")]
  public partial class FriendOperationArg : global::ProtoBuf.IExtensible
  {
    public FriendOperationArg() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _isAdd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAdd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAdd
    {
      get { return _isAdd; }
      set { _isAdd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendOperationRes")]
  public partial class FriendOperationRes : global::ProtoBuf.IExtensible
  {
    public FriendOperationRes() {}
    
    private int _ErrCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ErrCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrCode
    {
      get { return _ErrCode; }
      set { _ErrCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}