//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/FriendInfo.proto
namespace proto.FriendInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfoArg")]
  public partial class FriendInfoArg : global::ProtoBuf.IExtensible
  {
    public FriendInfoArg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfoRes")]
  public partial class FriendInfoRes : global::ProtoBuf.IExtensible
  {
    public FriendInfoRes() {}
    
    private int _ErrCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ErrCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrCode
    {
      get { return _ErrCode; }
      set { _ErrCode = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInfo> _FriendList = new global::System.Collections.Generic.List<PlayerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"FriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInfo> FriendList
    {
      get { return _FriendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private bool _isFriend;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFriend
    {
      get { return _isFriend; }
      set { _isFriend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}