//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Match.proto
namespace proto.Match
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchArg")]
  public partial class MatchArg : global::ProtoBuf.IExtensible
  {
    public MatchArg() {}
    
    private bool _isBeginGame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isBeginGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBeginGame
    {
      get { return _isBeginGame; }
      set { _isBeginGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchRes")]
  public partial class MatchRes : global::ProtoBuf.IExtensible
  {
    public MatchRes() {}
    
    private bool _isBeginGame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isBeginGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBeginGame
    {
      get { return _isBeginGame; }
      set { _isBeginGame = value; }
    }
    private int _Score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private string _PlayerUsername;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PlayerUsername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlayerUsername
    {
      get { return _PlayerUsername; }
      set { _PlayerUsername = value; }
    }
    private int _selfHp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selfHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfHp
    {
      get { return _selfHp; }
      set { _selfHp = value; }
    }
    private int _selfEnergy = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"selfEnergy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfEnergy
    {
      get { return _selfEnergy; }
      set { _selfEnergy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}